RESUME_SCHEMA = {
    "classification": "",
    "name": "",
    "email": "",
    "phone": "",
    "profile_links": {},
    "technical_skills": [],
    "soft_skills": [],
    "education": [],
    "projects": [],
    "experience": [],
    "internships": [],
    "certifications": [],
    "languages": [],
    "hobbies": [],
    "summary": "",
    "current_location": "",
    "current_ctc": "",
    "expected_ctc": "",
    "notice_period": "",
    "work_mode": "",
    "preferred_location": "",
    "video_summary" : ""
}
